from pathlib import Path
p=Path('components/StoryExperience.tsx');s=p.read_text(encoding='utf-8');s=s.replace("import CinematicScene", "import {Transit,BirthdayWish} from './StoryMoments';\nimport CinematicScene");s=s.replace('~{value}<small>','~{value.toLocaleString("en-IN")}<small>');s=s.replace('Proof that this gift<br/><em>came with miles.</em>','Not for a vacation.<br/><em>For one birthday gift.</em>');s=s.replace('<div className="proof-cards">','<h2 className="proof-heading documentary-heading">The screenshots don’t show the tiredness.<br/><em>But they show how far.</em></h2><div className="document-facts"><p>TRAIN <strong>MAQ HYB Special</strong></p><p>DEPARTURE <strong>04 SEP 2026</strong></p></div><div className="proof-cards">');s=s.replace('Scroll to see the surprise','Begin the journey');s=s.replace('<Distance/><CinematicScene','<Distance/><Transit/><CinematicScene');s=s.replace('<section className="section gift-reveal">','<section className="section suspense"><Reveal><p>Colour after colour.</p></Reveal><Reveal><p>Shop after shop.</p></Reveal><Reveal><p>Not just anything.</p><h2>It had to feel right.</h2></Reveal><Reveal><p>It had to be for her.</p><h2><em>Adya.</em></h2></Reveal></section><section className="section gift-reveal">')
a=s.index('<section className="section gift-reveal">');b=s.index('<section className="section birthday',a)
s=s[:a]+'''<CinematicScene category="bangle_reveal" className="bangle-climax"><Reveal><p className="eyebrow">ONE JOURNEY, ONE REASON</p><div className="climax-lines"><p>1,200 kilometres.</p><p>22+ hours.</p><p>One city.</p><p>One search.</p></div><h2>One Lac bangle.<br/><em>For Adya.</em></h2><p className="scene-prose">The gift is small.<br/>The journey behind it wasn’t.</p></Reveal></CinematicScene><section className="section ivory gift-meaning"><Reveal><h2>I could have ordered<br/>something online.</h2><p>But I didn’t want your gift to arrive without a story.</p><h3>I wanted to go there.<br/>Choose it.<br/>Carry it back.</h3><p>And give you something that had already travelled before it reached your hands.</p><p>So whenever you look at it…<br/>I hope you don’t only see a bangle.</p><h3><em>I hope you remember how much you mean to me.</em></h3></Reveal></section>'''+s[b:]
a=s.index('<section className="section birthday');b=s.index('<section className="section ivory short-timeline',a);s=s[:a]+'<BirthdayWish/>'+s[b:]
s=s.replace('<h2>{c.timeline}</h2>','<p>But the truth is…</p><h2>This journey didn’t really begin in Coimbatore.</h2>');s=s.replace('<footer><Reveal>', '<section className="section callback"><Reveal><h2>Maybe that’s why 1,200 kilometres<br/><em>didn’t feel that far.</em></h2><p>Because this journey started long before the train did.</p></Reveal></section><footer className="final-vow"><Reveal>');a=s.index('<footer className="final-vow">');s=s[:a]+'''<footer className="final-vow"><Reveal><p>From 03.06.2017…</p><p>…to 1,200 kilometres for a birthday gift.</p><h2>I’d still choose the journey.<br/><em>I’d still choose you.</em></h2><p>Happy Birthday, Adya.</p><span>21.02.2022 — still us.</span></Reveal></footer></main></>}
'''
p.write_text(s,encoding='utf-8')
p=Path('content/story.ts');s=p.read_text(encoding='utf-8').replace("start: 'This gift started here.', decision: 'At the station. With one decision.'", "start: 'This gift started before the shop.', decision: 'Before the bangle. Before Hyderabad.'").replace("onward:'To go all the way.'","onward:'It started with a ticket. And one very long journey.'").replace("destination:'And then…'","destination:'Eventually…'").replace("effort:'Not a random stop.'","effort:'But Hyderabad wasn’t the destination. Not exactly.'").replace("more:'A place chosen for one special gift.'","more:'This was where the search really began.'").replace("label:'The first time I saw you.'","label:'The first time I saw you. 5th standard.'").replace("label:'I told you my love.'","label:'The day I finally told you. 9th standard.'");p.write_text(s,encoding='utf-8')
p=Path('app/layout.tsx');s=p.read_text(encoding='utf-8').replace("import { Music }", "import StoryNav from '@/components/StoryNav';\nimport { Music }").replace('<body>{children}', '<body><StoryNav/>{children}');p.write_text(s,encoding='utf-8')
p=Path('components/CinematicScene.tsx');s=p.read_text(encoding='utf-8').replace('1.06+Math.abs(p)*.04','1+Math.abs(p)*.03');p.write_text(s,encoding='utf-8')
p=Path('components/MemoryPage.tsx');s=p.read_text(encoding='utf-8');s=s.replace("<>Not every hero shot<br/>was <em>perfect.</em></>","<>The <em>Bloopers.</em></>").replace("<>A few moments.<br/><em>All ours.</em></>","<>Photo<em>booth.</em></>").replace('Behind the effort… there were also these moments.','Because the 1,200 km journey wasn’t cinematic every second.').replace('Little pieces of a story worth keeping.','Some memories deserve their own wall.');s=s.replace('<button onClick={()=>setIndex(i)}', '''<button onPointerMove={e=>{if(e.pointerType!=='mouse'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.transform=`perspective(700px) rotateY(${(e.clientX-r.left-r.width/2)/45}deg) rotateX(${-(e.clientY-r.top-r.height/2)/65}deg)`}} onPointerLeave={e=>{e.currentTarget.style.transform='none'}} onClick={()=>setIndex(i)}''');p.write_text(s,encoding='utf-8')
