from pathlib import Path
p=Path('content/story.ts');s=p.read_text(encoding='utf-8');s=s.replace("'Not every gift begins in a shop.'","'Not every gift begins in a store.'").replace("start: 'This wasn’t an online order.', decision: 'This gift started with a decision.'","start: 'This gift started here.', decision: 'At the station. With one decision.'").replace("destination:'The destination wasn’t random.'","destination:'And then…'").replace("specific:'More specifically…'","specific:'The destination had a reason.'").replace("effort:'Because some gifts deserve effort.'","effort:'Not a random stop.'").replace("more:'And some people deserve even more.'","more:'A place chosen for one special gift.'").replace("giftNote:'Small gift. Big journey.'","giftNote:'Small gift. Big journey. Chosen with effort.'")
s=s.replace("'journey_start' | 'km_proof' | 'train_journey'", "'train_start' | 'journey_proof' | 'train_story'").replace("'bangle_search' | 'final_bangle'", "'charminar_portraits' | 'bangle_reveal'")
p.write_text(s,encoding='utf-8')
p=Path('components/Shared.tsx');s=p.read_text(encoding='utf-8').replace("category==='final_bangle'","category==='bangle_reveal'");p.write_text(s,encoding='utf-8')
p=Path('components/StoryExperience.tsx');s=p.read_text(encoding='utf-8');s=s.replace('02 / THE DISTANCE','03 / THE PROOF').replace('<Secret message="And I’d probably travel it again.">','<h2 className="proof-heading">Proof that this gift<br/><em>came with miles.</em></h2><Secret message="And I’d probably travel it again.">').replace('<Photos category="km_proof" label="TOTAL KILOMETRES — YOUR PROOF PHOTOGRAPH"/>','<div className="proof-stats"><p><span>BOARDING</span>{story.origin}</p><p><span>TRAVEL TIME</span>22+ hours</p><p><span>DESTINATION</span>{story.destination}</p></div>');s=s.replace('<div className="route-caption">','<div className="proof-cards"><Photos category="journey_proof" label="JOURNEY PROOF"/></div><div className="route-caption">')
s=s.replace('category="journey_start"','category="train_start"').replace('category="train_journey"','category="train_story"');s=s.replace('<Distance/>','');s=s.replace('03 / THE FIRST MILES','02 / THE FIRST MILES');s=s.replace('<CinematicScene category="hyderabad"','<Distance/><CinematicScene category="hyderabad"')
start=s.index('<section className="section ivory selection">');end=s.index('<section className="section gift-reveal">',start)
s=s[:start]+'''<section className="section ivory personal-arrival"><Reveal><p className="eyebrow">06 / MORE THAN ARRIVING</p><div className="selection-heading"><h2>I didn’t come this far<br/><em>just to arrive.</em></h2><p className="scene-prose">I came looking for something worthy of {story.herName}.</p></div><Photos category="charminar_portraits" label="CHARMINAR PORTRAITS"/></Reveal></section>
'''+s[end:]
s=s.replace('category="final_bangle"','category="bangle_reveal"').replace('<Photos category="couple" label="A PHOTOGRAPH OF YOU TWO"/>','');s=s.replace('<span>Happy Birthday.</span>','<span>Happy Birthday.</span><small className="end-credit">Made with love, miles, and memories.</small>')
p.write_text(s,encoding='utf-8')
p=Path('components/CinematicScene.tsx');s=p.read_text(encoding='utf-8');s=s.replace('<div className="scene-background">','{asset&&<div className="scene-ambient" aria-hidden="true"><Image src={asset.file} alt="" fill sizes="100vw" style={{objectFit:"cover"}}/></div>}<div className="scene-background">');p.write_text(s,encoding='utf-8')
